global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'shortener'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8080']  # puerto que usas en el navegador
